name: Run Tests

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 1


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        cache: 'pip'
        # cache-dependency-path: 'requirements*.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Mock
      run: |
        echo MOCKING STUFF
        
    - name: Test with pytest
      env:
        PYTHONPATH: src
      run: |
        echo github ref is = ${{ github.ref }}
        pytest tests
